### ISSUE TITLE
Error with CUDA 11.1

### ISSUE THREAD

**Issue by ebartrum** [autonomousvision/graf#5]
I ran train.py with celebA. Used the conda env, with CUDA 11.1, and got this error:
`
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    x_real = get_nsamples(train_loader, ntest)
  File "/home/ed/Documents/repos/graf/graf/utils.py", line 11, in get_nsamples
    x_next = next(iter(data_loader))
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ed/Documents/repos/graf/graf/datasets.py", line 41, in __getitem__
    img = self.transform(img)
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 615, in forward
    if torch.rand(1) < self.p:
  File "/home/ed/.conda/envs/graf/lib/python3.8/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
`

**Comment by ebartrum** [comment]
Seems to work when this line is commented out of train.py, may still be worth looking into though 
` num_workers=config['training']['nworkers']`
After commenting this line, num_workers = 0 (default) so no subprocesses spawned for dataloading, which instead happens in the main process. Possibly this may cause a bottleneck?

**Comment by katjaschwarz** [comment]
This seems to be a general problem, see e.g. [here](https://discuss.pytorch.org/t/runtimeerror-cannot-re-initialize-cuda-in-forked-subprocess-to-use-cuda-with-multiprocessing-you-must-use-the-spawn-start-method/14083/3) for a workaround.

**Comment by NIRVANALAN** [comment]
Also run into this error, cuda=10.1.  Likely to be triggered by the ```Lambda()``` in ```transforms()```. 
To work around:
1. add ```mp.set_start_method('spawn')``` in main() function
2. replace ```Lambda()``` with ```Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))```. I think they are basically the same.
